
export const SET_BOOKS = 'SET_BOOKS';
export const SET_SEARCH_RESULTS = 'SET_SEARCH_RESULTS';
export const ADD_BOOK = 'ADD_BOOK';
export const UPDATE_BOOK = 'UPDATE_BOOK';
export const REMOVE_BOOK = 'REMOVE_BOOK';
export const TOGGLE_FAVORITE = 'TOGGLE_FAVORITE';
export const SET_LOADING = 'SET_LOADING';
export const SET_ERROR = 'SET_ERROR';

export const SET_LISTS = 'SET_LISTS';
export const CREATE_LIST = 'CREATE_LIST';
export const DELETE_LIST = 'DELETE_LIST';
export const UPDATE_LIST = 'UPDATE_LIST';
export const ADD_BOOK_TO_LIST = 'ADD_BOOK_TO_LIST';
export const REMOVE_BOOK_FROM_LIST = 'REMOVE_BOOK_FROM_LIST';


export const SET_READING_SESSIONS = 'SET_READING_SESSIONS';
export const ADD_READING_SESSION = 'ADD_READING_SESSION';
export const UPDATE_READING_PROGRESS = 'UPDATE_READING_PROGRESS';